[project]
name = 'Entropy-Optimization-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.temporal-energy-redistribution]
path = 'contracts/temporal-energy-redistribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.universal-state-tracking]
path = 'contracts/universal-state-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
